// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtDolJtqJXQ8Ea8DKMJf4DJIR2_QuF-Xk',
    appId: '1:245698838678:android:25f3833c027f8c6d0f82b7',
    messagingSenderId: '245698838678',
    projectId: 'xmed-1b5bb',
    storageBucket: 'xmed-1b5bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb6-XFvclRgzky4h6c40l_D-79Ol-Rqhc',
    appId: '1:245698838678:ios:012c298377ba3f7a0f82b7',
    messagingSenderId: '245698838678',
    projectId: 'xmed-1b5bb',
    storageBucket: 'xmed-1b5bb.appspot.com',
    iosBundleId: 'com.example.xmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb6-XFvclRgzky4h6c40l_D-79Ol-Rqhc',
    appId: '1:245698838678:ios:9d353dc83cd703e50f82b7',
    messagingSenderId: '245698838678',
    projectId: 'xmed-1b5bb',
    storageBucket: 'xmed-1b5bb.appspot.com',
    iosBundleId: 'com.example.xmed.RunnerTests',
  );
}
